### ISSUE TITLE
Question: .RES unpacker (quickbms)

### ISSUE THREAD

**Issue by antooni007** [itsmeft24/cars-research#6]
Hi, I'm thinking of reviving the cars game modding community. I'm gathering some tools to help me get started. One tool I wasn't able to find back is the .RES file unpacker plugin for QuickBMS. According to the Cars game modding fan wiki, it should be on this link: http://forum.xentax.com/viewtopic.php?p=73164#p73164, but this forum is offline unfortunately. 

I was wondering whether you had this file lying around somewhere? Would be amazing if it doesn't go lost forever!

Thanks in advance.

**Comment by itsmeft24** [comment]
hi! for extracting .RES files via QuickBMS, you can download the ``rainbow_studios.bms`` script from [aluigi's website](https://aluigi.altervista.org/bms/rainbow_studios.bms). however, if you're trying to extract an entire streaming package (.str/.res) you'll need a different tool to finish the job (i technically haven't finished it yet and it only works on files from certain platforms >.<, but the codes up [here](https://github.com/itsmeft24/soiboy)).

since you've mentioned reviving the community, i highly recommend joining [this discord server](https://discord.gg/gXC8fXYq) as it's where most mod development for the trilogy games takes place. it's also where we discuss RE'ing these games!
